config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD

  resources :gossips do
 resources :comments
end

  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'
  root 'static_pages#home'
=======
  get '/', to: 'static_pages#home'
  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :gossips do
    resources :comments
  end
>>>>>>> 6b28e9f3d1ae41a2f5d092f49dba7f416a17d98d
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  has_many :like, as: :likeable
end

app/models/gossip.rb
class Gossip < ApplicationRecord
<<<<<<< HEAD
  belongs_to :user, optional:true
  has_and_belongs_to_many :tags
  has_many :comments
  has_many :likes
=======
  belongs_to :user
  has_and_belongs_to_many :tags
  has_many :comments
  has_many :likes, as: :likeable
>>>>>>> 6b28e9f3d1ae41a2f5d092f49dba7f416a17d98d
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :gossips
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :username,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
  format: { with: VALID_EMAIL_REGEX },
  uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :gossips
  has_many :likes
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
<<<<<<< HEAD
  def create
  @gossip = Gossip.find(params[:gossip_id])
  @comment = @gossip.comments.create(params[:comment].permit(:anonymous_commentor, :content))
  redirect_to gossip_path(@gossip)
end
=======

  def new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.gossip_id = params[:gossip_id]
    @comment.save
    redirect_to gossip_path(@comment.gossip)
  end

  def edit
    @comment = Comment.find(params[:id])
    @gossip = Gossip.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to gossip_path(@comment.gossip)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.delete
    redirect_to gossips_path(@comment.gossip)
  end

  def comment_params
    params.require(:comment).permit(:anonymous_commentor, :content)
  end
>>>>>>> 6b28e9f3d1ae41a2f5d092f49dba7f416a17d98d

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  def index
    @gossip = Gossip.all
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.create(title: params["gossip"]["title"], content: params["gossip"]["content"], anonymous_gossiper: params["gossip"]["anonymous_gossiper"])
    redirect_to @gossip
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comment = Comment.new
    @comment.gossip_id = @gossip.id
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    gossip_params = params.require(:gossip).permit(:title,:content,:anonymous_gossiper)
    @gossip.update(gossip_params)
    redirect_to @gossip
  end

<<<<<<< HEAD
  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    gossip_params = params.require(:gossip).permit(:title,:content,:anonymous_gossiper)
    @gossip.update(gossip_params)
    redirect_to @gossip
  end

=======
>>>>>>> 6b28e9f3d1ae41a2f5d092f49dba7f416a17d98d
  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.delete
    redirect_to gossips_path
  end

<<<<<<< HEAD
  def index
    @gossip = Gossip.all
  end

=======
>>>>>>> 6b28e9f3d1ae41a2f5d092f49dba7f416a17d98d
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  end

  def contact
  end

  def team
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create(username: params["user"]["username"], email: params["user"]["email"], password: params["user"]["password"])
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<hr>
<ul>

<p>Author : <%= comment.anonymous_commentor %>
<li><%= comment.content %></li>
<p>posted <%= time_ago_in_words(comment.created_at) %> ago</p>
</ul>
<hr>

app/views/comments/_form.html.erb
<%= form_for([@gossip,@gossip.comments.build]) do |f| %>
<%= label_tag 'anonymous_commentor:' %>
<%= f.text_field :anonymous_commentor, placeholder: 'username', class: "form-control", id: "formGroupExampleInput2" %>
<br />

<%= label_tag 'content:' %>
<%= f.text_area :content, placeholder: 'Your content...', class: "form-control", id: "formGroupExampleInput2" %>

<br />
<%= f.submit "Add the Gossip", class: "btn btn-success"  %>
<% end %>

app/views/comments/edit.html.erb
<h1> Edit a comment</h1>
<div style='width: 80%; margin-left: 30px; margin-top: 30px;'>
  <%= form_for [@gossip, @comment] do |f| %>
  <%= label_tag 'Author:' %>
  <%= f.text_field :anonymous_commentor, class: "form-control", id: "formGroupExampleInput2" %>
  <br><br>
  <%= label_tag 'Comment:' %>
  <%= f.text_area :content, class: "form-control", id: "formGroupExampleInput2" %>
  <br><br>
  <%= f.submit "Edit the Gossip", class: "btn btn-success"  %>
<% end %>

app/views/gossips/_comment.html.erb
<div class="card-comment">
<div class="card w-50">
 <div class="card-body">
   <h5 class="card-title"><%= comment.anonymous_commentor %></h5>
   <p class="card-text"><%= comment.content %></p>
   <p class='card-time'>Created @<%= comment.created_at %></p>
    <p class ='card-time'>Updated @<%= comment.updated_at %></p>
     <a href="<%=edit_gossip_comment_path(@gossip.id,comment.id)%>" class="btn btn-primary">Edit</a>
     <a href="<%= gossip_comment_path(@gossip.id,comment.id)%>" class="btn btn-danger" data-confirm="Are you sure ?" data-method="DELETE">Delete</a>
 </div>
</div>
</div>
<br>

app/views/gossips/edit.html.erb
<div style='width: 80%; margin-left: 30px; margin-top: 30px;'>
  <%= form_for @gossip do |f| %>
  <%= label_tag 'Title:' %>
  <%= f.text_field :title, placeholder: 'Your title...', class: "form-control", id: "formGroupExampleInput2" %>
  <br /><br />
<<<<<<< HEAD
  <%= label_tag 'Author:' %>
 <%= f.text_field :anonymous_gossiper, placeholder: 'Your username...', class: "form-control", id: "formGroupExampleInput2" %>

  <br /><br />
  <%= label_tag 'Content:' %>
  <%= f.text_area :content, placeholder: 'Your content...', class: "form-control", id: "formGroupExampleInput2" %>

  <br /><br />
  <%= f.submit "Add the Gossip", class: "btn btn-success"  %>
  <a href="<%= gossip_path(@gossip.id)%>" class="btn btn-danger" data-confirm="Are you sure ?" data-method="DELETE">Delete</a></p>

=======
  <%= label_tag 'Content:' %>
  <%= f.text_area :content, placeholder: 'Your content...', class: "form-control", id: "formGroupExampleInput2" %>
  <br /><br />
    <%= label_tag 'Author:' %>
  <%= f.text_field :anonymous_gossiper, placeholder: 'Your username...', class: "form-control", id: "formGroupExampleInput2" %>
  <br /><br />
  <%= f.submit "Add the Gossip", class: "btn btn-success"  %>
>>>>>>> 6b28e9f3d1ae41a2f5d092f49dba7f416a17d98d
<% end %>

app/views/gossips/index.html.erb
<<<<<<< HEAD

<div class="newgossip"> <a href="<%= new_gossip_path %>" class="btn btn-success">Create a Gossip</a> </div>
<div class=index>
  <% @gossip.each do |g|%>
  <div class="card" style="width: 32rem;">
    <div class="card-body">
       <h5 class="card-title"><a href="/gossips/<%=g.id%>">Gossip n°<%= g.id%></a></h5>
        <p class="card-title"><%= g.title %></p>
      <p class="card-text"><%= g.anonymous_gossiper %> </p>
        <p class="card-text"><%= g.content %> </p>
          <p> <%= g.comments.count %> Comments<p>
     <a href="gossips/<%= g.id %>/edit" class="btn btn-primary">Edit this Gossip</a>
      <a href="<%= gossip_path(g.id)%>" class="btn btn-danger" data-confirm="Are you sure ?" data-method="DELETE">Delete</a></p>

  </div>
  </div>
  </div>
  <div>

  <% end %>
</div>
</div>
=======
<h1> The Gossip Project</h1><br>
<% @gossip.each do |gossip| %>
<div class="card-box">
<div class="card border-light mb-3" style="max-width: 18rem;">
<div class="card-header"><a href="/gossips/<%=gossip.id%>"> Gossip n°<%=gossip.id%></a></div>
<div class="card-body">
 <h5 class="card-title"><%= gossip.anonymous_gossiper %></h5>
 <p class="card-text"><%= gossip.content%></p>
 <a href="<%= edit_gossip_path(gossip.id)%>" class="btn btn-primary">Edit</a>
 <a href="<%= gossip_path(gossip.id)%>" class="btn btn-danger" data-confirm="Are you sure ?" data-method="DELETE">Delete</a>
</div>
</div>
</div>
<% end %>
>>>>>>> 6b28e9f3d1ae41a2f5d092f49dba7f416a17d98d

app/views/gossips/new.html.erb
<div style='width: 20%; margin-left: 30px; margin-top: 30px;'>
  <%= form_for @gossip do |f| %>
  <%= label_tag 'Title:' %>
  <%= f.text_field :title, placeholder: 'Your title...', class: "form-control", id: "formGroupExampleInput2" %>
  <br /><br />
  <%= label_tag 'Author:' %>
 <%= f.text_field :anonymous_gossiper, placeholder: 'Your username...', class: "form-control", id: "formGroupExampleInput2" %>

  <br /><br />
  <%= label_tag 'Content:' %>
  <%= f.text_area :content, placeholder: 'Your content...', class: "form-control", id: "formGroupExampleInput2" %>
<<<<<<< HEAD

=======
  <br /><br />
    <%= label_tag 'Author:' %>
  <%= f.text_field :anonymous_gossiper, placeholder: 'Your username...', class: "form-control", id: "formGroupExampleInput2" %>
>>>>>>> 6b28e9f3d1ae41a2f5d092f49dba7f416a17d98d
  <br /><br />
  <%= f.submit "Add the Gossip", class: "btn btn-success"  %>
<% end %>

app/views/gossips/show.html.erb
<h1>GOSSIP <%=params[:id]%></h1>
  <p>
<<<<<<< HEAD

<a href="/gossips" class="btn btn-primary">return to all gossips</a

    <div class="card-box">      <div class="card border-light mb-3" style="max-width: 18rem;">
        <div class="card-header">Gossip n°<%=@gossip.id%></div>
        <div class="card-body">
          <h5 class="card-title"><%= @gossip.title %></h5>
         <p class="card-text"><%= @gossip.anonymous_gossiper%></p>
          <p class="card-text"><%= @gossip.content%></p>

          <p class="card-text"><%= @gossip.created_at%></p>
          <a href="<%= gossip_path(@gossip.id)%>" class="btn btn-danger" data-confirm="Are you sure ?" data-method="DELETE">Delete</a></p>
          <a href="<%= edit_gossip_path(@gossip.id)%>" class="btn btn-primary">Edit</a>





        </div>
      </div>
    </div>
  </p>





  <p> <%= @gossip.comments.count %> Comments<p>
      <%= render @gossip.comments %>
      <p>Add a Comment:</p> <br><br>
<%= render 'comments/form' %>
=======
    <div class="card-box">
      <div class="card border-light mb-3" style="max-width: 18rem;">
        <div class="card-header"><%=@gossip.title%></div>
        <div class="card-body">
          <p class="card-text"><%= @gossip.content%></p>
          <p class="card-text"><%= @gossip.anonymous_gossiper%></p>
          <p class="card-time">Created @<%= @gossip.created_at%></p>
          <p class="card-time">Updated @<%= @gossip.updated_at%></p>
          <p>Comments (<%= @gossip.comments.size %>)</p>
        </div>
      </div>
    </div>
    <h2> Comments : </h2>
    <%= render partial: 'gossips/comment', collection: @gossip.comments.reverse%>
  <%= render partial: 'layouts/form' %>
>>>>>>> 6b28e9f3d1ae41a2f5d092f49dba7f416a17d98d

app/views/layouts/_form.html.erb
<div style='width: 80%; margin-left: 30px; margin-top: 30px;'>
  <%= form_for [@gossip, @comment] do |f| %>
  <%= label_tag 'Author:' %>
  <%= f.text_field :anonymous_commentor, placeholder: 'Your username...', class: "form-control", id: "formGroupExampleInput2" %>
  <br><br>
  <%= label_tag 'Comment:' %>
  <%= f.text_area :content, placeholder: 'Your comment...', class: "form-control", id: "formGroupExampleInput2" %>
  <br><br>
  <%= f.submit "Add a comment", class: "btn btn-success"  %>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">The Gossip Project</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
<<<<<<< HEAD

        <a class="nav-item nav-link" href="/gossips">Gossip</a>
=======
        <a class="nav-item nav-link active" href="/gossips">Index<span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link" href="/gossips/new">Create a Gossip</a>
>>>>>>> 6b28e9f3d1ae41a2f5d092f49dba7f416a17d98d
        <a class="nav-item nav-link" href="/team">Team</a>
        <a class="nav-item nav-link disabled" href="/contact">Contact</a>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/static_pages/contact.html.erb
<<<<<<< HEAD
<h1 class= "titre">📞CONTACT THE BOSS📞</h1>
<h2 class = "titre">If you want to contact us :</h2>
<br>
<ul >
<li> <a href="https://www.thehackingproject.org/">Contact</a> </li>
<li><a href="mailto:bonjour@thehackingproject.org">Email</a> </li>
</ul>
=======
<h1>Contact</h1>
<p>If you have any questions click <a href="https://www.facebook.com/ysaline.wizzy">here</a> !</p>
>>>>>>> 6b28e9f3d1ae41a2f5d092f49dba7f416a17d98d

app/views/static_pages/home.html.erb
<<<<<<< HEAD

<h1 class="titre">👂 🤫👂THE GOSSIP PROJECT👂 🤫👂</h1>
<h2 class="titre">‍👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻💻WELCOME/BIENVENUE💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻👩‍💻</h2>


<div class =home>
<div class="center jumbotron">
  <h2>Bienvenue !</h2>
  <h3>
    Ici, tu peux retrouver les moussaillons 🎓
  </h3>
  <%= link_to "Enregistre-toi !", '#', class: "btn btn-lg btn-primary" %>
</div>
</div>
=======
<p class='button'><%= link_to "SIGN UP", 'users/new', class: "btn btn-lg btn-primary" %></p>
<p class='button'><%= link_to "SIGN IN", '/login', class: "btn btn-lg btn-primary" %></p>
<h1>Welcome !</h1>
>>>>>>> 6b28e9f3d1ae41a2f5d092f49dba7f416a17d98d

app/views/static_pages/team.html.erb
<<<<<<< HEAD
<h1 class= "titre">👂TEAM👂</h1>
<h2 class= "titre">Bienvenido voici notre équipe lol mdr 😇❤️😻 : </h2>
<ul>
<li> Ysaline <a href = "https://github.com/Ysalien">🤨 </a> </li>
<li> Nikita  <a href = "https://github.com/nikitavasilev">🤨</a></li>
<li>Nathaniel<a href= "https://github.com/Natdenice">🤨</a></li>
<li> Arthur  <a href ="https://github.com/tutus06/">🤨</a></li>
<li> Thomas  <a href ="https://github.com/TomacTh/">🤨 </a> </li>
</ul>
=======
<h1>Team</h1>
<h5>This website has been released by THP Nice</h5>
<p>
  <ul>
    <li><a href='https://github.com/ysalien'>Ysaline</a></li>
    <li><a href='https://github.com/Natdenice'>Nat</a></li>
    <li><a href='https://github.com/TomacTh'>Tom</a></li>
    <li><a href='https://github.com/NikitaVasilev'>Nikita</a></li>
    <li><a href='https://github.com/tutus06'>Arthur</a></li></ul>
    </p>
>>>>>>> 6b28e9f3d1ae41a2f5d092f49dba7f416a17d98d

app/views/users/new.html.erb
<h1> Create an account</h1>
<div style='width: 20%; margin-left: 30px; margin-top: 30px;'>
  <%= form_for @user do |f| %>
  <%= label_tag 'Username :' %>
  <%= f.text_field :username, placeholder: "Your username..", class: "form-control", id: "formGroupExampleInput2" %>
  <br><br>
  <%= label_tag 'Email adress :' %>
  <%= f.text_field :email, placeholder: "Your email...", class: "form-control", id: "formGroupExampleInput2" %>
  <br><br>
  <%= label_tag 'Password :' %>
  <%= f.text_field :password, placeholder: "Your password...", class: "form-control", type: "password", id: "formGroupExampleInput2" %>
  <br><br>
  <%= f.submit "Create an account", class: "btn btn-success"  %>
<% end %>